# Generated by Django 3.2.7 on 2022-03-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qrmenu', '0043_alter_customerorder_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackOrder',
            fields=[
                ('order_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pack_type', models.CharField(max_length=5)),
                ('order_amount', models.CharField(max_length=25)),
                ('isPaid', models.BooleanField(default=False)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrmenu.restaurantdetail')),
            ],
        ),
    ]
