# Generated by Django 2.1.15 on 2022-03-21 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('qrmenu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packorder',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrmenu.RestaurantDetail'),
        ),
    ]
