# Generated by Django 3.2.7 on 2022-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packorder',
            options={'ordering': ['-order_date']},
        ),
        migrations.AddField(
            model_name='packorder',
            name='currency',
            field=models.CharField(blank=True, default='inr', max_length=5, null=True),
        ),
    ]
