# Generated by Django 3.2.7 on 2021-11-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurantdetail',
            name='image',
            field=models.ImageField(null=True, upload_to='restaurant_image'),
        ),
        migrations.AlterField(
            model_name='restaurantdetail',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantdetail',
            name='logo',
            field=models.ImageField(null=True, upload_to='restaurant_logo'),
        ),
        migrations.AlterField(
            model_name='restaurantdetail',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('price', models.FloatField(null=True)),
                ('desc', models.TextField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qrmenu.menucategory')),
            ],
        ),
    ]
