# Generated by Django 3.2.7 on 2021-11-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0002_auto_20211126_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='display',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='img',
            field=models.ImageField(null=True, upload_to='item_imgs'),
        ),
    ]
