# Generated by Django 3.2.7 on 2021-12-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0003_auto_20211130_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
