# Generated by Django 3.2.7 on 2021-12-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0004_auto_20211203_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img',
            field=models.ImageField(default='default.png', upload_to='item_imgs'),
        ),
    ]
