# Generated by Django 3.2.7 on 2021-12-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0005_alter_menuitem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='img',
            field=models.ImageField(default='item_imgs/default.png', upload_to='item_imgs'),
        ),
    ]
