# Generated by Django 3.2.7 on 2021-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0007_auto_20211215_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
