# Generated by Django 3.2.7 on 2021-12-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0008_restaurantdetail_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='unique_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
