# Generated by Django 3.2.7 on 2021-12-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0009_restaurantdetail_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetail',
            name='unique_id',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True, unique=True),
        ),
    ]
