# Generated by Django 3.2.7 on 2021-12-28 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0010_alter_restaurantdetail_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='qrmenu.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30, null=True)),
                ('table_no', models.IntegerField(null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('ordered_menu', models.ManyToManyField(to='qrmenu.OrderedMenu')),
            ],
        ),
    ]
