# Generated by Django 3.2.7 on 2022-01-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0011_customerorder_orderedmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='allowCalltoWaiter',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='allowCustomerOrder',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
