# Generated by Django 3.2.7 on 2022-01-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0012_auto_20220104_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdetail',
            name='allowCalltoWaiter',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='restaurantdetail',
            name='allowCustomerOrder',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('zipcode', models.CharField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('restaurant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='qrmenu.restaurantdetail')),
            ],
        ),
    ]
