# Generated by Django 3.2.7 on 2022-01-06 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0014_auto_20220106_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='restaurant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='qrmenu.restaurantdetail'),
        ),
    ]
