# Generated by Django 3.2.7 on 2022-01-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0015_alter_billingdetail_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='country',
            field=models.CharField(choices=[('india', 'India'), ('usa', 'United State of America'), ('uae', 'United Arab Emirates'), ('uk', 'United Kingdom')], default='india', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='AccountSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('currency', models.CharField(choices=[('inr', 'INR'), ('usd', 'USD'), ('eur', 'EUR')], default='inr', max_length=15)),
                ('menu_layout', models.CharField(choices=[('list', 'List Layout'), ('grid', 'Grid Layout'), ('box', 'Box Layout')], default='list', max_length=15)),
                ('menu_language', models.CharField(choices=[('tamil', 'Tamil'), ('english', 'English'), ('sakovia', 'Sakovia')], default='tamil', max_length=15)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qrmenu.restaurantdetail')),
            ],
        ),
    ]
