# Generated by Django 3.2.7 on 2022-01-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0017_restaurantdetail_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetail',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
