# Generated by Django 3.2.7 on 2022-01-08 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0019_auto_20220107_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 10, 30, 33, 340989)),
        ),
    ]
