# Generated by Django 3.2.7 on 2022-01-08 05:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0020_customerorder_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='customerorder',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qrmenu.restaurantdetail'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 8, 10, 58, 22, 59388)),
        ),
    ]
