# Generated by Django 3.2.7 on 2022-01-17 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0021_auto_20220108_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerorder',
            options={'ordering': ['status', '-timestamp']},
        ),
        migrations.AddField(
            model_name='customerorder',
            name='order_type',
            field=models.CharField(choices=[('dinein', 'Dinein'), ('delivery', 'Delivery'), ('pickup', 'Pickup')], default='dinein', max_length=15),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 15, 45, 27, 623738)),
        ),
    ]
