# Generated by Django 3.2.7 on 2022-01-21 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('qrmenu', '0022_auto_20220117_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsetting',
            name='currency_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('SAR', 'SAR')], default='INR', max_length=15),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 12, 21, 49, 850533)),
        ),
    ]
