# Generated by Django 3.2.7 on 2022-01-21 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0024_auto_20220121_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetting',
            name='currency',
            field=models.CharField(blank=True, choices=[('INR', 'INR'), ('USD', 'USD'), ('SAR', 'SAR')], default='INR', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 15, 7, 33, 961460)),
        ),
    ]
