# Generated by Django 3.2.7 on 2022-01-21 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0025_auto_20220121_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsetting',
            name='currency',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 15, 11, 3, 940488)),
        ),
    ]
