# Generated by Django 3.2.7 on 2022-01-21 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0026_auto_20220121_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetting',
            name='menu_language',
            field=models.CharField(blank=True, choices=[('tamil', 'Tamil'), ('english', 'English'), ('sakovia', 'Sakovia')], default='tamil', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='menu_layout',
            field=models.CharField(blank=True, choices=[('list', 'List Layout'), ('grid', 'Grid Layout'), ('box', 'Box Layout')], default='list', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 21, 15, 13, 54, 486923)),
        ),
    ]
