# Generated by Django 3.2.7 on 2022-01-24 06:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0027_auto_20220121_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 11, 43, 38, 347377)),
        ),
        migrations.CreateModel(
            name='ScanCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qrmenu.restaurantdetail')),
            ],
        ),
    ]
