# Generated by Django 3.2.7 on 2022-01-24 07:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
        ('qrmenu', '0028_auto_20220124_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetting',
            name='currency_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 13, 23, 37, 452820)),
        ),
    ]
