# Generated by Django 3.2.7 on 2022-01-24 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0029_auto_20220124_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 13, 29, 15, 497355)),
        ),
    ]
