# Generated by Django 3.2.7 on 2022-01-24 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0030_alter_customerorder_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 24, 15, 33, 27, 684787)),
        ),
    ]
