# Generated by Django 3.2.7 on 2022-02-07 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0031_auto_20220124_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='is_packactive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='pack_type',
            field=models.CharField(blank=True, default='Free Trial', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='menu_language',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('tamil', 'Tamil'), ('sakovia', 'Sakovia')], default='english', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 15, 38, 31, 316194)),
        ),
    ]
