# Generated by Django 3.2.7 on 2022-02-08 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0032_auto_20220207_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 8, 16, 53, 2, 44265)),
        ),
        migrations.AlterField(
            model_name='restaurantdetail',
            name='pack_type',
            field=models.CharField(blank=True, choices=[('free_pack', 'Free Pack'), ('monthly_pack', 'Monthly Pack'), ('yearly_pack', 'Yearly Pack')], default='free_pack', max_length=15, null=True),
        ),
    ]
