# Generated by Django 3.2.7 on 2022-02-09 09:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0033_auto_20220208_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_menus', models.PositiveIntegerField(blank=True, default=0)),
                ('total_scans', models.PositiveIntegerField(blank=True, default=0)),
                ('pack_type', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantdetail',
            name='is_packactive',
        ),
        migrations.RemoveField(
            model_name='restaurantdetail',
            name='pack_type',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 9, 14, 39, 28, 926499)),
        ),
        migrations.AddField(
            model_name='restaurantdetail',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qrmenu.pack'),
        ),
    ]
