# Generated by Django 3.2.7 on 2022-02-10 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0035_auto_20220209_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='total_tables',
            field=models.PositiveIntegerField(blank=True, default=5),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 13, 11, 55, 474861)),
        ),
    ]
