# Generated by Django 3.2.7 on 2022-02-16 09:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0036_auto_20220210_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 15, 25, 21, 713066)),
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('initiate', 'Initiate'), ('pending', 'Pending'), ('resolved', 'Resolved')], default='initiate', max_length=20)),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qrmenu.restaurantdetail')),
            ],
        ),
    ]
