# Generated by Django 3.2.7 on 2022-02-18 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0038_auto_20220218_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 18, 10, 7, 38, 327013)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
