# Generated by Django 3.2.7 on 2022-03-02 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0039_auto_20220218_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdetail',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoice_pdfs'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 9, 58, 9, 981426)),
        ),
    ]
