# Generated by Django 3.2.7 on 2022-03-07 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0041_auto_20220304_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 7, 14, 45, 25, 638185)),
        ),
    ]
