# Generated by Django 3.2.7 on 2022-03-10 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0042_auto_20220307_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 12, 51, 47, 982061)),
        ),
    ]
