# Generated by Django 3.2.7 on 2022-03-14 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0043_alter_customerorder_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='country',
            field=models.CharField(choices=[('india', 'India'), ('usa', 'United State of America'), ('uae', 'United Arab Emirates'), ('uk', 'United Kingdom'), ('sa', 'Saudi Arabia')], default='india', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 16, 18, 51, 57501)),
        ),
    ]
