# Generated by Django 3.2.7 on 2022-03-17 04:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0044_auto_20220314_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 10, 28, 52, 579329)),
        ),
        migrations.AlterField(
            model_name='orderedmenu',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qrmenu.menuitem'),
        ),
        migrations.AlterField(
            model_name='restaurantdetail',
            name='total_tables',
            field=models.PositiveIntegerField(default=5, null=True),
        ),
    ]
