# Generated by Django 3.2.7 on 2022-03-17 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0045_auto_20220317_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 17, 16, 16, 24, 347635)),
        ),
    ]
