# Generated by Django 2.1.15 on 2022-04-12 06:18

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0054_auto_20220407_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetail',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 11, 47, 14, 117413)),
        ),
    ]
