# Generated by Django 2.1.15 on 2022-04-12 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0055_auto_20220412_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='name_fr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_hi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_fr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_hi',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='name_ru',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='menu_language',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('ta', 'Tamil'), ('hi', 'Hindi'), ('ar', 'Arabic'), ('ru', 'Russian'), ('fr', 'French')], default='en-us', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 15, 19, 8, 732426)),
        ),
    ]
