# Generated by Django 2.1.15 on 2022-04-14 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrmenu', '0056_auto_20220412_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='menucategory',
            name='name_ta',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_en_us',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_hi',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='name_ta',
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 14, 13, 14, 54, 754918)),
        ),
    ]
